/// Flutter icons MedicineIcons
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MedicineIcons
///      fonts:
///       - asset: fonts/MedicineIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MedicineIcons {
  MedicineIcons._();

  static const _kFontFam = 'MedicineIcons';

  static const IconData pill = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData syrup = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData tablet = const IconData(0xe802, fontFamily: _kFontFam);
}
